# Generated by Django 5.2.3 on 2025-07-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('single', 'Один вариант'), ('multiple', 'Несколько вариантов')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
